//
//  LocalizationKey.swift
//  foodmonster
//
//  Created by Egor Bryzgalov on 3/10/23.
//

import Foundation

enum LocalizationDefaultValues: String {
    
    case LOCALIZATION_FILE = "Localization"

    case SAVE = "Save recipe"
    case OPS = "Oooops ..."
    case ANONYMOUS_MESSAGE = "Please, log in or create new acccount for start building you cook book "
    case CANCEL = "Cancel"
    case LOG_IN = "Login"
    case MIN = "min."
    case PORTIONS = "portions"
    case STEP = "STEP"
    case INGREDIENT = "Ingredients"
    case SERVES = "serves"
    case NO_NEW_PASSWORD = "Looks like you didn't set new password"
    case PASSWORD_MISMATCH = "Password mismatch"
    case TAKE_PHOTO = "Take Photo"
    case MISS_CAMERA = "Missing camera"
    case CAMERA_PHOTO = "You can't take photo, there is no camera"
    case CHOOSE_FROM_LIB = "Choose From Library"
    case REMOVE_PHOTO = "Remove Photo"
    case SEARCH_RECIPE = "Search my recipes"
    case TERMS = "Terms and Conditions"
    case TERMS_WARN = "By continuing to register, you accept the terms and conditions"
    case SHOW = "Show"
    case SOMETHING_WAS_WRONG = "Something was wrong. We work on it. Please try again little later"
    case NEW_RECIPE = "New Recipe"
    case EDIT_RECIPE = "Edit Recipe"
    case VERIFICATION_ERROR = "Verification Error"
    case VERIFICATION_ERROR_MESSAGE = "Your email was not verified. Please check you email and complete registration"
    case RESEND = "Send Again"
    case TOO_MANY_REQUESTS = "Too many requests"
    case SUCCESS = "Success"
    case RECIPE_UPDATE = "Recipe is updated"
    case SWEET = "Sweet"
    case ALERT_NEW_RECIPE_MESSAGE = "Please select a category of dish and/or name your recipe"
    case TOO_LOW_INGR_STEPS_TITLE = "Quite interesting"
    case TOO_LOW_INGR_STEPS_MESSAGE = "Looks like you do not have name or not enough ingredients or cooking steps for your masterpeace"
    case SAVE_ANYWAY = "Save Anyway"
    case RECIPE_SAVED = "Recipe is saved"
    case RECIPE_NAME = "Recipe Name"
    case COOK_TIME = "Cook Time"
    case NO_PERMISSION = "No Permission"
    case MOVE_TO_SETTINGS = "Would you like to go settings and chenge permissions?"
    case GO = "Let's go!"
    case CATEGORY_SEARCH_PLACEHOLDER = "Type name and search recipe"
    case CHECK_PASS = "Check your password"
    case CHECK_EMAIL = "Check email address"
    case ACCOUNT = "Account"
    case EXTRAS = "Extras"
    case ACC_DELETION_TITLE = "Account deletion"
    case ACC_DELETION_MESSAGE = "By deleting your account, you will permanently lose access to your recipes. Are you sure you want to delete your account?"
    case DELETE = "Delete"
    case EMPTY_FIELD = "One of the fields empty"
    case EMAIL_NOT_SAME = "Email is not comparable"
    case PASS_RESSETED = "Password is resetted"
    case INSTRUCTION_SENT_1 = "Instructions was sent to"
    case INSTRUCTION_SENT_2 = "Please follow to instruction to create new password"
    case EXTRA_ITEM = "Extra items"
    case INGR_SECTION_HEADER = "Ingredients (at least 1)"
    case DIRECTION_SECTION_HEADER = "Directions (at least 2)"

    case APPETIZER = "Appetizer"
    case BAKING = "Baking"
    case BREAD = "Bread"
    case DESSERT = "Dessert"
    case DRINKS = "Drinks"
    case LUNCH = "Lunch"
    case MEAT = "Meat"
    case GLUTEN_FREE = "Gluten Free"
    case PASTA = "Pasta"
    case SALAD = "Salad"
    case SEAFOOD = "Seafood"
    case SIDE = "Side"
    case SOUP = "Soup"
    case SOUCE = "Sauce"
    case VEGETARION = "Vegetarian"
    case VEGAN = "Vegan"
    
}
